# Setup

title:            'Edmundo Santos, Web Designer & Front-end Developer based in Dublin, Ireland'
description:      'I design performance driven, responsive websites that work seamless across devices. For me, common sense wins against intricate ideas, and I love to take the latter and turn into clean and simple interfaces.'

url:              http://edmundojr.com
baseurl:          ""

permalink:        /:categories/:title/

paginate:         5
paginate_path:    "/blog/page:num/"

author:
  name:           'Edmundo Santos'
  email:          hello@edmundojr.com
  facebook:       edmundojr
  github:         edmundojr
  instagram:      edmundojr_
  stackoverflow:  users/1034869/edmundojr
  twitter:        edmundojr_

analytics:        UA-1068613-7

disqus:           edmundojr

# Dependencies

markdown:         redcarpet
gems:             [jekyll-paginate]

exclude:          ['gulpfile.js', 'package.json', 'node_modules', 'assets/scss']
keep_files:       ['_site/assets/css', '_site/.nojekyll']